# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dkdrive_2.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1107, 728)
        MainWindow.setMinimumSize(QtCore.QSize(1107, 728))
        MainWindow.setMaximumSize(QtCore.QSize(1107, 728))
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.func_table = QtWidgets.QTabWidget(self.centralwidget)
        self.func_table.setGeometry(QtCore.QRect(0, 0, 1111, 701))
        self.func_table.setMinimumSize(QtCore.QSize(0, 0))
        self.func_table.setMaximumSize(QtCore.QSize(1111, 701))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.func_table.setFont(font)
        self.func_table.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.func_table.setStyleSheet("font: 24pt \"Agency FB\";")
        self.func_table.setObjectName("func_table")
        self.my_drive = QtWidgets.QWidget()
        self.my_drive.setObjectName("my_drive")
        self.current_dir_edit = QtWidgets.QLineEdit(self.my_drive)
        self.current_dir_edit.setGeometry(QtCore.QRect(70, 10, 591, 21))
        self.current_dir_edit.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"color: rgb(0, 85, 255);")
        self.current_dir_edit.setObjectName("current_dir_edit")
        self.current_dir_label = QtWidgets.QLabel(self.my_drive)
        self.current_dir_label.setGeometry(QtCore.QRect(0, 10, 71, 21))
        self.current_dir_label.setStyleSheet("font: 11pt \"Agency FB\";")
        self.current_dir_label.setObjectName("current_dir_label")
        self.search_edit = QtWidgets.QLineEdit(self.my_drive)
        self.search_edit.setGeometry(QtCore.QRect(910, 10, 131, 21))
        self.search_edit.setStyleSheet("font: 9pt \"微软雅黑\";\n"
"color: rgb(0, 85, 255);")
        self.search_edit.setObjectName("search_edit")
        self.search_btn = QtWidgets.QPushButton(self.my_drive)
        self.search_btn.setGeometry(QtCore.QRect(1050, 10, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.search_btn.setFont(font)
        self.search_btn.setStyleSheet("font: 9pt \"Agency FB\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/my_pic/search_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_btn.setIcon(icon)
        self.search_btn.setObjectName("search_btn")
        self.return_btn = QtWidgets.QPushButton(self.my_drive)
        self.return_btn.setGeometry(QtCore.QRect(670, 10, 51, 23))
        self.return_btn.setStyleSheet("font: 9pt \"Agency FB\";")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/my_pic/return_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.return_btn.setIcon(icon1)
        self.return_btn.setObjectName("return_btn")
        self.upload_file = QtWidgets.QPushButton(self.my_drive)
        self.upload_file.setGeometry(QtCore.QRect(740, 10, 81, 23))
        self.upload_file.setStyleSheet("font: 9pt \"Agency FB\";")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/my_pic/upload_icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.upload_file.setIcon(icon2)
        self.upload_file.setObjectName("upload_file")
        self.upload_dir = QtWidgets.QPushButton(self.my_drive)
        self.upload_dir.setGeometry(QtCore.QRect(820, 10, 81, 23))
        self.upload_dir.setStyleSheet("font: 9pt \"Agency FB\";")
        self.upload_dir.setIcon(icon2)
        self.upload_dir.setObjectName("upload_dir")
        self.func_table.addTab(self.my_drive, "")
        self.transfer_widget = QtWidgets.QWidget()
        self.transfer_widget.setObjectName("transfer_widget")
        self.left_widget = QtWidgets.QListWidget(self.transfer_widget)
        self.left_widget.setGeometry(QtCore.QRect(0, 0, 141, 131))
        self.left_widget.setObjectName("left_widget")
        item = QtWidgets.QListWidgetItem()
        self.left_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.left_widget.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.left_widget.addItem(item)
        self.right_widget = QtWidgets.QStackedWidget(self.transfer_widget)
        self.right_widget.setGeometry(QtCore.QRect(140, 0, 961, 581))
        self.right_widget.setObjectName("right_widget")
        self.download_page = QtWidgets.QWidget()
        self.download_page.setObjectName("download_page")
        self.download_table = QtWidgets.QTableWidget(self.download_page)
        self.download_table.setGeometry(QtCore.QRect(0, 0, 941, 561))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.download_table.setFont(font)
        self.download_table.setObjectName("download_table")
        self.download_table.setColumnCount(5)
        self.download_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.download_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.download_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.download_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.download_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.download_table.setHorizontalHeaderItem(4, item)
        self.right_widget.addWidget(self.download_page)
        self.upload_page = QtWidgets.QWidget()
        self.upload_page.setObjectName("upload_page")
        self.upload_table = QtWidgets.QTableWidget(self.upload_page)
        self.upload_table.setGeometry(QtCore.QRect(0, 0, 941, 561))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.upload_table.setFont(font)
        self.upload_table.setObjectName("upload_table")
        self.upload_table.setColumnCount(4)
        self.upload_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.upload_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.upload_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.upload_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.upload_table.setHorizontalHeaderItem(3, item)
        self.right_widget.addWidget(self.upload_page)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.finish_table = QtWidgets.QTableWidget(self.page_3)
        self.finish_table.setGeometry(QtCore.QRect(0, 0, 941, 561))
        font = QtGui.QFont()
        font.setFamily("Agency FB")
        font.setPointSize(24)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.finish_table.setFont(font)
        self.finish_table.setObjectName("finish_table")
        self.finish_table.setColumnCount(6)
        self.finish_table.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.finish_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.finish_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.finish_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.finish_table.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.finish_table.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.finish_table.setHorizontalHeaderItem(5, item)
        self.right_widget.addWidget(self.page_3)
        self.func_table.addTab(self.transfer_widget, "")
        self.file_share = QtWidgets.QWidget()
        self.file_share.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.file_share.setObjectName("file_share")
        self.func_table.addTab(self.file_share, "")
        self.others = QtWidgets.QWidget()
        self.others.setObjectName("others")
        self.func_table.addTab(self.others, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1107, 23))
        self.menubar.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.menubar.setFont(font)
        self.menubar.setAutoFillBackground(True)
        self.menubar.setObjectName("menubar")
        self.menufile = QtWidgets.QMenu(self.menubar)
        self.menufile.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menufile.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.menufile.setAutoFillBackground(True)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/my_pic/logo-splash.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menufile.setIcon(icon3)
        self.menufile.setToolTipsVisible(False)
        self.menufile.setObjectName("menufile")
        self.menuhelp = QtWidgets.QMenu(self.menubar)
        self.menuhelp.setObjectName("menuhelp")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action123 = QtWidgets.QAction(MainWindow)
        self.action123.setObjectName("action123")
        self.action123123 = QtWidgets.QAction(MainWindow)
        self.action123123.setObjectName("action123123")
        self.actionguanyu = QtWidgets.QAction(MainWindow)
        self.actionguanyu.setObjectName("actionguanyu")
        self.menu_file = QtWidgets.QAction(MainWindow)
        self.menu_file.setObjectName("menu_file")
        self.action2 = QtWidgets.QAction(MainWindow)
        self.action2.setObjectName("action2")
        self.action2_2 = QtWidgets.QAction(MainWindow)
        self.action2_2.setObjectName("action2_2")
        self.action3 = QtWidgets.QAction(MainWindow)
        self.action3.setObjectName("action3")
        self.actionopen = QtWidgets.QAction(MainWindow)
        self.actionopen.setShortcutVisibleInContextMenu(False)
        self.actionopen.setObjectName("actionopen")
        self.actionsave = QtWidgets.QAction(MainWindow)
        self.actionsave.setObjectName("actionsave")
        self.actioncontect_us = QtWidgets.QAction(MainWindow)
        self.actioncontect_us.setObjectName("actioncontect_us")
        self.menufile.addAction(self.actionopen)
        self.menufile.addAction(self.actionsave)
        self.menufile.addSeparator()
        self.menuhelp.addAction(self.actioncontect_us)
        self.menubar.addAction(self.menuhelp.menuAction())
        self.menubar.addAction(self.menufile.menuAction())

        self.retranslateUi(MainWindow)
        self.func_table.setCurrentIndex(0)
        self.right_widget.setCurrentIndex(1)
        self.left_widget.currentRowChanged['int'].connect(self.right_widget.setCurrentIndex)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "dkdrive"))
        self.current_dir_edit.setText(_translate("MainWindow", "/"))
        self.current_dir_label.setText(_translate("MainWindow", "当前目录："))
        self.search_btn.setText(_translate("MainWindow", "搜索"))
        self.return_btn.setText(_translate("MainWindow", "返回"))
        self.upload_file.setText(_translate("MainWindow", "文件上传"))
        self.upload_dir.setText(_translate("MainWindow", "目录上传"))
        self.func_table.setTabText(self.func_table.indexOf(self.my_drive), _translate("MainWindow", "我的网盘"))
        __sortingEnabled = self.left_widget.isSortingEnabled()
        self.left_widget.setSortingEnabled(False)
        item = self.left_widget.item(0)
        item.setText(_translate("MainWindow", "正在下载"))
        item = self.left_widget.item(1)
        item.setText(_translate("MainWindow", "正在上传"))
        item = self.left_widget.item(2)
        item.setText(_translate("MainWindow", "传输完成"))
        self.left_widget.setSortingEnabled(__sortingEnabled)
        item = self.download_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "file_name"))
        item = self.download_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "loading"))
        item = self.download_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "delete"))
        item = self.download_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "stop"))
        item = self.download_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "locate"))
        item = self.upload_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "file_name"))
        item = self.upload_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "loading"))
        item = self.upload_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "delete"))
        item = self.upload_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "stop"))
        item = self.finish_table.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "file_name"))
        item = self.finish_table.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "loading"))
        item = self.finish_table.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "delete"))
        item = self.finish_table.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "stop"))
        item = self.finish_table.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "locate"))
        item = self.finish_table.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "time"))
        self.func_table.setTabText(self.func_table.indexOf(self.transfer_widget), _translate("MainWindow", "传输列表"))
        self.func_table.setTabText(self.func_table.indexOf(self.file_share), _translate("MainWindow", " 好友分享"))
        self.func_table.setTabText(self.func_table.indexOf(self.others), _translate("MainWindow", "others"))
        self.menufile.setTitle(_translate("MainWindow", "file"))
        self.menuhelp.setTitle(_translate("MainWindow", "help"))
        self.action123.setText(_translate("MainWindow", "123"))
        self.action123123.setText(_translate("MainWindow", "123123"))
        self.actionguanyu.setText(_translate("MainWindow", "guanyu"))
        self.menu_file.setText(_translate("MainWindow", "1"))
        self.action2.setText(_translate("MainWindow", "你好"))
        self.action2_2.setText(_translate("MainWindow", "2"))
        self.action3.setText(_translate("MainWindow", "3"))
        self.actionopen.setText(_translate("MainWindow", "user_name"))
        self.actionsave.setText(_translate("MainWindow", "setting"))
        self.actioncontect_us.setText(_translate("MainWindow", "handbook"))

import photo_1_rc
